Update CosmosGettingStarted.csproj
In some cases, to avoid error CS5001: Program does not contain a static 'Main' method suitable for an entry point you need to set the C# version in the project to minimum 7.1 (or latest available)